services:
  cms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smanka-cms-app
    restart: always
    env_file:
      - .env
    environment:
      - PORT=3001
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public&sslmode=disable&connect_timeout=30
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3001:3001"
    # Volume hanya untuk logs atau upload jika diperlukan, 
    # prisma sudah ada di dalam image hasil build optimal
    # Jika Anda butuh database lokal (SQLite), aktifkan volume di bawah:
    # volumes:
    #   - ./prisma/dev.db:/app/prisma/dev.db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

