services:
  cms-app:
    build: .
    container_name: smanka-cms-app
    restart: always
    environment:
      - PORT=3000
    env_file:
      - .env
    ports:
      - "127.0.0.1:3001:3000" # Map ke port 3001 di Host
    volumes:
      - ./prisma:/app/prisma

# HAPUS ATAU KOMENTAR SERVICE NGINX DI SINI
